"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _app_dashboard from './app-dashboard.bones.json'
import _app_expenses from './app-expenses.bones.json'
import _app_expense_form from './app-expense-form.bones.json'
import _app_budget_form from './app-budget-form.bones.json'
import _app_reports from './app-reports.bones.json'
import _app_settings from './app-settings.bones.json'
import _app_shared from './app-shared.bones.json'
import _app_friends from './app-friends.bones.json'
import _app_friend_detail from './app-friend-detail.bones.json'
import _app_shared_expense_form from './app-shared-expense-form.bones.json'
import _auth_form from './auth-form.bones.json'
import _marketing_hero from './marketing-hero.bones.json'

configureBoneyard({"color":"oklch(0.97 0 0)","darkColor":"oklch(0.269 0 0)","animate":"shimmer","shimmerColor":"oklch(0.985 0 0)","darkShimmerColor":"oklch(0.32 0 0)","speed":"2s","shimmerAngle":110})

registerBones({
  "app-dashboard": _app_dashboard,
  "app-expenses": _app_expenses,
  "app-expense-form": _app_expense_form,
  "app-budget-form": _app_budget_form,
  "app-reports": _app_reports,
  "app-settings": _app_settings,
  "app-shared": _app_shared,
  "app-friends": _app_friends,
  "app-friend-detail": _app_friend_detail,
  "app-shared-expense-form": _app_shared_expense_form,
  "auth-form": _auth_form,
  "marketing-hero": _marketing_hero,
})
